services:
  db_dj_auth_audit:
     container_name: db_dj_auth_audit
     image: postgres
     restart: always
     environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASS}
     ports:
      - "${TEST_DB_PORT}:5432"
#     networks:
#        - internal